services:
  - type: web
    name: rag-documind
    env: java
    plan: free
    buildCommand: mvn -DskipTests package
    startCommand: java -jar target/*.jar
    envVars:
      - key: MONGO_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: VECTOR_FILE_PATH
        value: /data/vectors.json
      - key: PORT
        sync: false
